export const URL_INTRO_TEXT = 'https://successorsf1.com';

export const URL_INTRO_ENTER_END = 20;
export const URL_INTRO_MORPH_START = 12;
export const URL_INTRO_MORPH_END = 36;
export const URL_INTRO_TYPE_START = 36;
export const URL_INTRO_FRAMES_PER_CHAR = 2;
export const URL_INTRO_TYPE_END =
  URL_INTRO_TYPE_START + URL_INTRO_TEXT.length * URL_INTRO_FRAMES_PER_CHAR;
export const URL_INTRO_HOLD_DURATION = 12;
export const URL_INTRO_PUSH_START =
  URL_INTRO_TYPE_END + URL_INTRO_HOLD_DURATION;
export const URL_INTRO_TRANSITION_DURATION = 30;
export const URL_INTRO_SCENE_DURATION =
  URL_INTRO_PUSH_START + URL_INTRO_TRANSITION_DURATION;
